--- 
- hosts: 172.31.41.248
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    notify: restart webserver 

  - name: i want to copy index file into ansible node
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: restart webserver  
    
  handlers:
  - name: restart webserver 
    service: 
      name: apache2
      state: present 