--- 
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu nodes
    apt:
      name: "{{installjavaubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
    
  - name: install java on redhat nodes
    yum:
      name: "{{installjavaredhet}}"
      state: present
    when: ansible_os_family =="RedHat"