--- 
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu node
    apt:
      name: "{{myjavaforubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
    
  - name: install java on redhat node
    yum:
      name: "{{myjavaforRedHat}}"
      state: present
    when: ansible_os_family =="RedHat"