--- 
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu nodes
    apt:
      name: "{{myjavaforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
    
  - name: install java on redhat nodes
    yum:
      name: "{{myjavaforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"