---
- hosts: 172.31.41.248
  become: yes
  tasks:
  - name: install git 
    apt:
      name:
      state: present
    tags: mygit

  - name: install tree 
    apt:
      name: tree 
      state: present 
    tags: mytree

  - name: install wget
    apt:
      name: wget
      state: present 
    tags: mywget

      
      
