---
- hosts: 172.31.47.193
  become: yes
  tasks:
  - name: install git 
    apt:
      name:
      state: present

  - name: install tree 
    apt:
      name: tree 
      state: present 

  - name: install wget
    apt:
      name: wget
      state: present 
      
      
