--- 
- name: create a new tomcat group
  group:
    name: tomcat 
    state: present

- name: create user 
  user:
    name: tomcat
    shell: /bin/false
    groups: tomcat 
    home: /opt/tomcat
    state: present 